#数据库驱动配置
spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keshe?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
  resources:
    static-locations: classpath:/
#    文件上下传大小配置
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  thymeleaf:
    cache: false

#    日志配置
logging:
  level:
    com:
      bysj:
        qiu: debug


#必须要扫描到mapper的maybatis配置文件，不然dao层将无法使用sql语句  在yml文件下的目录里找
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
